terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }
  }

  backend "s3" {
    # Values supplied via -backend-config flags or terraform/backend.conf
    # See README.md "Bootstrap Sequence" section
    key            = "gitops-sre-demo/terraform.tfstate"
    encrypt        = true
    use_lockfile   = true
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Project    = var.project_name
      ManagedBy  = "terraform"
      Repository = "${var.github_org}/${var.github_repo}"
    }
  }
}

# ---------------------------------------------------------------------------
# Account guard — hard-fail if the active AWS account does not match expected
# ---------------------------------------------------------------------------

data "aws_caller_identity" "current" {}

locals {
  account_ok = var.aws_account_id == "" || data.aws_caller_identity.current.account_id == var.aws_account_id
}

resource "null_resource" "account_guard" {
  count = local.account_ok ? 0 : 1

  provisioner "local-exec" {
    command = <<-EOT
      echo ""
      echo "  ERROR: Wrong AWS account!"
      echo "  Expected : ${var.aws_account_id}"
      echo "  Active   : ${data.aws_caller_identity.current.account_id}"
      echo "  Fix: export AWS_PROFILE=personal  (or aws configure --profile personal)"
      echo ""
      exit 1
    EOT
  }
}

# ---------------------------------------------------------------------------
# Data sources
# ---------------------------------------------------------------------------

# Latest Debian 12 (Bookworm) official AMI
data "aws_ami" "debian_12" {
  most_recent = true
  owners      = ["136693071363"] # Debian official AWS account

  filter {
    name   = "name"
    values = ["debian-12-amd64-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  filter {
    name   = "state"
    values = ["available"]
  }
}

# GitHub OIDC thumbprint fetched dynamically — no hardcoded value
data "tls_certificate" "github_oidc" {
  url = "https://token.actions.githubusercontent.com/.well-known/openid-configuration"
}

data "aws_vpc" "default" {
  default = true
}

# ---------------------------------------------------------------------------
# SSH Key Pair — generated by Terraform, private key stored in Secrets Manager
# Retrieve the key:  aws secretsmanager get-secret-value \
#   --secret-id <ssh_key_secret_arn output> \
#   --query SecretString --output text > /tmp/k3s.pem && chmod 600 /tmp/k3s.pem
# ---------------------------------------------------------------------------

resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "k3s" {
  key_name   = "${var.project_name}-k3s"
  public_key = tls_private_key.ssh.public_key_openssh

  tags = {
    Name = "${var.project_name}-k3s"
  }
}

resource "aws_secretsmanager_secret" "ssh_key" {
  name                    = "${var.project_name}/ec2-ssh-private-key"
  description             = "RSA private key for SSH access to the ${var.project_name} K3s node"
  recovery_window_in_days = 0 # Allow immediate deletion — demo environment
}

resource "aws_secretsmanager_secret_version" "ssh_key" {
  secret_id     = aws_secretsmanager_secret.ssh_key.id
  secret_string = tls_private_key.ssh.private_key_pem
}

# ---------------------------------------------------------------------------
# GitHub OIDC Identity Provider
# ---------------------------------------------------------------------------

resource "aws_iam_openid_connect_provider" "github" {
  url             = "https://token.actions.githubusercontent.com"
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.github_oidc.certificates[0].sha1_fingerprint]

  tags = {
    Name = "${var.project_name}-github-oidc"
  }
}

# ---------------------------------------------------------------------------
# Permission Boundary — caps max permissions any IAM role/user created by
# Terraform can ever hold. Prevents privilege escalation even if the
# github-actions role is fully compromised.
# Every aws_iam_role in this file must reference this boundary.
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "permission_boundary" {
  # EC2 operations only (this project never needs more)
  statement {
    sid    = "EC2"
    effect = "Allow"
    actions = [
      "ec2:*",
    ]
    resources = ["*"]
  }

  # Least-set IAM: only PassRole, only to the EC2 instance role
  statement {
    sid    = "IAMPassRole"
    effect = "Allow"
    actions = ["iam:PassRole"]
    resources = [
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${var.project_name}-ec2-instance",
    ]
  }

  # IAM read (for terraform plan)
  statement {
    sid    = "IAMRead"
    effect = "Allow"
    actions = [
      "iam:Get*",
      "iam:List*",
    ]
    resources = ["*"]
  }

  # Terraform state
  statement {
    sid    = "TerraformState"
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:PutObject",
      "s3:DeleteObject",
      "s3:ListBucket",
      "dynamodb:GetItem",
      "dynamodb:PutItem",
      "dynamodb:DeleteItem",
      "dynamodb:DescribeTable",
    ]
    resources = [
      "arn:aws:s3:::${var.tf_state_bucket}",
      "arn:aws:s3:::${var.tf_state_bucket}/*",
      "arn:aws:dynamodb:${var.aws_region}:${data.aws_caller_identity.current.account_id}:table/${var.tf_state_dynamodb_table}",
    ]
  }

  # Secrets Manager — SSH key only
  statement {
    sid    = "SecretsManager"
    effect = "Allow"
    actions = [
      "secretsmanager:CreateSecret",
      "secretsmanager:DeleteSecret",
      "secretsmanager:DescribeSecret",
      "secretsmanager:GetSecretValue",
      "secretsmanager:ListSecretVersionIds",
      "secretsmanager:PutSecretValue",
      "secretsmanager:RestoreSecret",
      "secretsmanager:TagResource",
      "secretsmanager:UpdateSecret",
    ]
    resources = [
      "arn:aws:secretsmanager:${var.aws_region}:${data.aws_caller_identity.current.account_id}:secret:${var.project_name}/*",
    ]
  }

  # SSM — required for AmazonSSMManagedInstanceCore to function on the EC2 instance
  # Without this the boundary would zero-out all SSM permissions (effective = policy ∩ boundary)
  statement {
    sid    = "SSM"
    effect = "Allow"
    actions = [
      "ssm:DescribeAssociation",
      "ssm:GetDeployablePatchSnapshotForInstance",
      "ssm:GetDocument",
      "ssm:DescribeDocument",
      "ssm:GetManifest",
      "ssm:GetParameter",
      "ssm:GetParameters",
      "ssm:ListAssociations",
      "ssm:ListInstanceAssociations",
      "ssm:PutInventory",
      "ssm:PutComplianceItems",
      "ssm:PutConfigurePackageResult",
      "ssm:UpdateAssociationStatus",
      "ssm:UpdateInstanceAssociationStatus",
      "ssm:UpdateInstanceInformation",
      "ssmmessages:CreateControlChannel",
      "ssmmessages:CreateDataChannel",
      "ssmmessages:OpenControlChannel",
      "ssmmessages:OpenDataChannel",
      "ec2messages:AcknowledgeMessage",
      "ec2messages:DeleteMessage",
      "ec2messages:FailMessage",
      "ec2messages:GetEndpoint",
      "ec2messages:GetMessages",
      "ec2messages:SendReply",
    ]
    resources = ["*"]
  }

  # STS — required for OIDC and caller-identity checks
  statement {
    sid    = "STS"
    effect = "Allow"
    actions = ["sts:GetCallerIdentity", "sts:AssumeRoleWithWebIdentity"]
    resources = ["*"]
  }
}

resource "aws_iam_policy" "permission_boundary" {
  name        = "${var.project_name}-permission-boundary"
  description = "Maximum permissions cap — attached as boundary on every IAM role this project creates"
  policy      = data.aws_iam_policy_document.permission_boundary.json

  tags = {
    Name = "${var.project_name}-permission-boundary"
  }
}

# ---------------------------------------------------------------------------
# IAM Role — APPLY role (main branch only, full write permissions)
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "github_actions_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      type        = "Federated"
      identifiers = [aws_iam_openid_connect_provider.github.arn]
    }

    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:aud"
      values   = ["sts.amazonaws.com"]
    }

    # Restrict to the main branch only — apply never runs on PRs
    condition {
      test     = "StringLike"
      variable = "token.actions.githubusercontent.com:sub"
      values   = ["repo:${var.github_org}/${var.github_repo}:ref:refs/heads/main"]
    }
  }
}

resource "aws_iam_role" "github_actions" {
  name                 = "${var.project_name}-github-actions"
  assume_role_policy   = data.aws_iam_policy_document.github_actions_assume.json
  permissions_boundary = aws_iam_policy.permission_boundary.arn

  tags = {
    Name = "${var.project_name}-github-actions"
  }
}

# ---------------------------------------------------------------------------
# IAM Role — PLAN role (any branch / PR, read-only)
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "github_plan_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      type        = "Federated"
      identifiers = [aws_iam_openid_connect_provider.github.arn]
    }

    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:aud"
      values   = ["sts.amazonaws.com"]
    }

    # Allow any branch/PR in this repo — plan is safe (read-only)
    condition {
      test     = "StringLike"
      variable = "token.actions.githubusercontent.com:sub"
      values   = ["repo:${var.github_org}/${var.github_repo}:*"]
    }
  }
}

resource "aws_iam_role" "github_plan" {
  name                 = "${var.project_name}-github-plan"
  assume_role_policy   = data.aws_iam_policy_document.github_plan_assume.json
  permissions_boundary = aws_iam_policy.permission_boundary.arn

  tags = {
    Name = "${var.project_name}-github-plan"
  }
}

# Read-only policy for plan role: describe EC2 + read state bucket only
data "aws_iam_policy_document" "github_plan_policy" {
  statement {
    sid    = "ReadOnlyEC2"
    effect = "Allow"
    actions = [
      "ec2:Describe*",
      "ec2:Get*",
      "ec2:List*",
    ]
    resources = ["*"]
  }

  statement {
    sid    = "ReadIAM"
    effect = "Allow"
    actions = [
      "iam:Get*",
      "iam:List*",
    ]
    resources = ["*"]
  }

  statement {
    sid    = "ReadStateBucket"
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:ListBucket",
    ]
    resources = [
      "arn:aws:s3:::${var.tf_state_bucket}",
      "arn:aws:s3:::${var.tf_state_bucket}/*",
    ]
  }

  statement {
    sid    = "ReadStateLock"
    effect = "Allow"
    actions = [
      "dynamodb:GetItem",
      "dynamodb:DescribeTable",
    ]
    resources = [
      "arn:aws:dynamodb:${var.aws_region}:*:table/${var.tf_state_dynamodb_table}",
    ]
  }

  statement {
    sid    = "ReadSecretsManager"
    effect = "Allow"
    actions = [
      "secretsmanager:DescribeSecret",
      "secretsmanager:ListSecretVersionIds",
    ]
    resources = [
      "arn:aws:secretsmanager:${var.aws_region}:*:secret:${var.project_name}/*",
    ]
  }
}

resource "aws_iam_role_policy" "github_plan" {
  name   = "${var.project_name}-github-plan-policy"
  role   = aws_iam_role.github_plan.id
  policy = data.aws_iam_policy_document.github_plan_policy.json
}

# Least-privilege policy: EC2 operations + state bucket access
data "aws_iam_policy_document" "github_actions_policy" {
  # EC2 permissions scoped to resources tagged by this project
  statement {
    sid    = "EC2TaggedResources"
    effect = "Allow"
    actions = [
      "ec2:RunInstances",
      "ec2:TerminateInstances",
      "ec2:StopInstances",
      "ec2:StartInstances",
      "ec2:ModifyInstanceAttribute",
      "ec2:CreateTags",
      "ec2:DeleteTags",
    ]
    resources = ["*"]
    condition {
      test     = "StringEquals"
      variable = "aws:ResourceTag/ManagedBy"
      values   = ["terraform"]
    }
  }

  # Read-only EC2 describe — no resource restriction needed
  statement {
    sid    = "EC2Describe"
    effect = "Allow"
    actions = [
      "ec2:Describe*",
      "ec2:Get*",
      "ec2:List*",
    ]
    resources = ["*"]
  }

  # Security group management
  statement {
    sid    = "EC2SecurityGroups"
    effect = "Allow"
    actions = [
      "ec2:AuthorizeSecurityGroupIngress",
      "ec2:AuthorizeSecurityGroupEgress",
      "ec2:RevokeSecurityGroupIngress",
      "ec2:RevokeSecurityGroupEgress",
      "ec2:CreateSecurityGroup",
      "ec2:DeleteSecurityGroup",
      "ec2:ModifySecurityGroupRules",
    ]
    resources = ["*"]
  }

  # IAM — only PassRole for the instance profile
  statement {
    sid    = "IAMPassRole"
    effect = "Allow"
    actions = ["iam:PassRole"]
    resources = [aws_iam_role.ec2_instance.arn]
  }

  # IAM instance profile management
  statement {
    sid    = "IAMInstanceProfile"
    effect = "Allow"
    actions = [
      "iam:AddRoleToInstanceProfile",
      "iam:CreateInstanceProfile",
      "iam:DeleteInstanceProfile",
      "iam:GetInstanceProfile",
      "iam:RemoveRoleFromInstanceProfile",
    ]
    resources = ["*"]
  }

  # Terraform state S3
  statement {
    sid    = "TerraformStateBucket"
    effect = "Allow"
    actions = [
      "s3:GetObject",
      "s3:PutObject",
      "s3:DeleteObject",
      "s3:ListBucket",
    ]
    resources = [
      "arn:aws:s3:::${var.tf_state_bucket}",
      "arn:aws:s3:::${var.tf_state_bucket}/*",
    ]
  }

  # Terraform state lock DynamoDB
  statement {
    sid    = "TerraformStateLock"
    effect = "Allow"
    actions = [
      "dynamodb:GetItem",
      "dynamodb:PutItem",
      "dynamodb:DeleteItem",
      "dynamodb:DescribeTable",
    ]
    resources = [
      "arn:aws:dynamodb:${var.aws_region}:*:table/${var.tf_state_dynamodb_table}",
    ]
  }

  # EC2 key pair management (Terraform creates/deletes the generated key pair)
  statement {
    sid    = "EC2KeyPairs"
    effect = "Allow"
    actions = [
      "ec2:CreateKeyPair",
      "ec2:DeleteKeyPair",
      "ec2:DescribeKeyPairs",
      "ec2:ImportKeyPair",
    ]
    resources = ["*"]
  }

  # Secrets Manager — read/write the SSH private key stored by Terraform
  statement {
    sid    = "SecretsManagerSSHKey"
    effect = "Allow"
    actions = [
      "secretsmanager:CreateSecret",
      "secretsmanager:DeleteSecret",
      "secretsmanager:DescribeSecret",
      "secretsmanager:GetSecretValue",
      "secretsmanager:ListSecretVersionIds",
      "secretsmanager:PutSecretValue",
      "secretsmanager:RestoreSecret",
      "secretsmanager:TagResource",
      "secretsmanager:UpdateSecret",
    ]
    resources = [
      "arn:aws:secretsmanager:${var.aws_region}:*:secret:${var.project_name}/*",
    ]
  }
}

resource "aws_iam_role_policy" "github_actions" {
  name   = "${var.project_name}-github-actions-policy"
  role   = aws_iam_role.github_actions.id
  policy = data.aws_iam_policy_document.github_actions_policy.json
}

# ---------------------------------------------------------------------------
# IAM Role — attached to the EC2 instance (for future SSM / CloudWatch use)
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "ec2_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "ec2_instance" {
  name                 = "${var.project_name}-ec2-instance"
  assume_role_policy   = data.aws_iam_policy_document.ec2_assume.json
  permissions_boundary = aws_iam_policy.permission_boundary.arn

  tags = {
    Name = "${var.project_name}-ec2-instance"
  }
}

resource "aws_iam_role_policy_attachment" "ec2_ssm" {
  role       = aws_iam_role.ec2_instance.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "ec2" {
  name = "${var.project_name}-ec2-profile"
  role = aws_iam_role.ec2_instance.name
}

# ---------------------------------------------------------------------------
# Security Group
# ---------------------------------------------------------------------------

resource "aws_security_group" "k3s" {
  name        = "${var.project_name}-k3s"
  description = "GitOps SRE Demo - K3s node"
  vpc_id      = data.aws_vpc.default.id

  # SSH — restricted to var.allowed_ssh_cidr
  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.allowed_ssh_cidr]
  }

  # HTTP
  ingress {
    description = "HTTP"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # HTTPS
  ingress {
    description = "HTTPS"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # Grafana NodePort
  ingress {
    description = "Grafana"
    from_port   = 3000
    to_port     = 3000
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # K3s API server
  ingress {
    description = "K3s API"
    from_port   = 6443
    to_port     = 6443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # ArgoCD NodePort
  ingress {
    description = "ArgoCD UI"
    from_port   = 32080
    to_port     = 32080
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # Kong API Gateway proxy NodePort
  ingress {
    description = "Kong Proxy"
    from_port   = 8000
    to_port     = 8000
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # Service Dashboard NodePort
  ingress {
    description = "Service Dashboard"
    from_port   = 8090
    to_port     = 8090
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    description = "All outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.project_name}-k3s"
  }
}

# ---------------------------------------------------------------------------
# EC2 Instance
# ---------------------------------------------------------------------------

locals {
  user_data = templatefile("${path.module}/user-data.sh", {
    github_org   = var.github_org
    github_repo  = var.github_repo
    project_name = var.project_name
    ghcr_token   = var.ghcr_token
  })
}

resource "aws_instance" "k3s" {
  ami                    = data.aws_ami.debian_12.id
  instance_type          = var.instance_type
  key_name               = aws_key_pair.k3s.key_name
  vpc_security_group_ids = [aws_security_group.k3s.id]
  iam_instance_profile   = aws_iam_instance_profile.ec2.name

  # Replace the instance (immutable) when user-data changes
  user_data_replace_on_change = true
  user_data                   = local.user_data

  root_block_device {
    volume_type           = "gp3"
    volume_size           = var.root_volume_size_gb
    delete_on_termination = true
    encrypted             = true

    tags = {
      Name = "${var.project_name}-root"
    }
  }

  metadata_options {
    http_tokens                 = "required" # IMDSv2 only — security best practice
    http_put_response_hop_limit = 2          # Allow pods on K3s to reach IMDS
    http_endpoint               = "enabled"
  }

  tags = {
    Name = "${var.project_name}-k3s-node"
  }

  lifecycle {
    create_before_destroy = true
  }
}
