apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: apps
  labels:
    app: service-a
spec:
  selector:
    app: service-a
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
