#!/usr/bin/env bash
# =============================================================================
# scripts/ai-sandbox-setup.sh
# =============================================================================
# Extracts a restricted kubeconfig for AI agent use (GitHub Copilot, local
# agents, etc.) from the ai-agent ServiceAccount token in the ai-sandbox
# namespace.
#
# The resulting kubeconfig:
#   ~/.kube/ai-sandbox/config
#
# …grants READ-ONLY access to the ai-sandbox namespace only.  No secrets,
# no exec, no cross-namespace visibility.
#
# Prerequisites:
#   kubectl apply -f k8s/aiops/ai-sandbox/rbac.yaml   (done by ArgoCD or manually)
#
# Usage:
#   chmod +x scripts/ai-sandbox-setup.sh
#   ./scripts/ai-sandbox-setup.sh
#   # then add to your shell — see scripts/ai-shell-guard.zsh
# =============================================================================

set -euo pipefail

NAMESPACE="ai-sandbox"
SA_NAME="ai-agent"
SECRET_NAME="ai-agent-token"
OUTPUT_DIR="${HOME}/.kube/ai-sandbox"
OUTPUT_FILE="${OUTPUT_DIR}/config"

echo "==> Verifying ai-sandbox RBAC is deployed..."
if ! kubectl get serviceaccount "${SA_NAME}" -n "${NAMESPACE}" &>/dev/null; then
  echo "ERROR: ServiceAccount '${SA_NAME}' not found in namespace '${NAMESPACE}'."
  echo "       Apply the RBAC manifest first:"
  echo "         kubectl apply -f k8s/aiops/ai-sandbox/rbac.yaml"
  exit 1
fi

echo "==> Waiting for token secret to be populated..."
for i in $(seq 1 15); do
  TOKEN=$(kubectl get secret "${SECRET_NAME}" -n "${NAMESPACE}" \
    -o jsonpath='{.data.token}' 2>/dev/null | base64 --decode 2>/dev/null || true)
  if [[ -n "${TOKEN}" ]]; then
    break
  fi
  echo "    ... waiting (${i}/15)"
  sleep 2
done

if [[ -z "${TOKEN:-}" ]]; then
  echo "ERROR: Token not populated after 30 s. Check secret:"
  echo "         kubectl describe secret ${SECRET_NAME} -n ${NAMESPACE}"
  exit 1
fi

# Extract cluster info from the currently active context
CLUSTER_SERVER=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')
CLUSTER_CA=$(kubectl config view --minify --flatten \
  -o jsonpath='{.clusters[0].cluster.certificate-authority-data}')

echo "==> Creating directory ${OUTPUT_DIR} (mode 700)..."
mkdir -p "${OUTPUT_DIR}"
chmod 700 "${OUTPUT_DIR}"

echo "==> Writing restricted kubeconfig to ${OUTPUT_FILE}..."
cat > "${OUTPUT_FILE}" <<EOF
# AI-Agent restricted kubeconfig — READ-ONLY, ai-sandbox namespace only
# Generated by scripts/ai-sandbox-setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT EXPAND PERMISSIONS — this file is intentionally limited.
apiVersion: v1
kind: Config
clusters:
  - name: ai-sandbox-cluster
    cluster:
      server: ${CLUSTER_SERVER}
      certificate-authority-data: ${CLUSTER_CA}
contexts:
  - name: ai-sandbox
    context:
      cluster: ai-sandbox-cluster
      namespace: ${NAMESPACE}
      user: ai-agent
current-context: ai-sandbox
users:
  - name: ai-agent
    user:
      token: ${TOKEN}
EOF

chmod 600 "${OUTPUT_FILE}"

echo ""
echo "✅  AI-sandbox kubeconfig written: ${OUTPUT_FILE}"
echo ""
echo "Next steps:"
echo "  1. Source the shell guard into your shell:"
echo "       echo 'source \$(pwd)/scripts/ai-shell-guard.zsh' >> ~/.zshrc"
echo "       source ~/.zshrc"
echo ""
echo "  2. Verify the restricted context (should only see ai-sandbox ns):"
echo "       KUBECONFIG=${OUTPUT_FILE} kubectl get pods -A"
echo "       KUBECONFIG=${OUTPUT_FILE} kubectl get pods -n apps  # should be denied"
echo ""
echo "  3. The shell guard auto-sets KUBECONFIG=~/.kube/ai-sandbox/config"
echo "     when GitHub Copilot agent sessions are detected (see ai-shell-guard.zsh)."
