apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.55.0"
    helm:
      releaseName: loki
      valueFiles:
        - $values/k8s/observability/loki/values.yaml
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: "6.55.0"
      helm:
        releaseName: loki
        valueFiles:
          - $values/k8s/observability/loki/values.yaml
    - repoURL: https://github.com/YOUR-GITHUB-ORG/gitops-sre-demo.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: lgtm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
